// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fozcumigqcpnpabrvyam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvemN1bWlncWNwbnBhYnJ2eWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTEyNTgsImV4cCI6MjA2MDgyNzI1OH0.Xe6roVZDdL9T459QpxIcvVsKqqgWGdJrAabVg3eDR5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);